name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 10 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [ "python-3.11", "python-3.12" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "bake_file=${{ matrix.provider }}/env.hcl" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Copy files
        run: |
          cp -rf files/* ${{ matrix.provider }}/
          tree .
      - name: Build and push
        uses: docker/bake-action@v4
        with:
          pull: true
          push: true
          no-cache: true
          files: docker-bake.hcl,${{ steps.vars.outputs.bake_file }}
